services:
  db:
    image: postgres:17.5
    container_name: db
    environment:
      POSTGRES_DB: SaveApi
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: