services:
  db:
    image: postgres:17.5
    container_name: db
    environment:
      POSTGRES_DB: taskDb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d taskDb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - db_app

  dbSecurity:
    image: postgres:17.5
    container_name: dbSecurity
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbSecurity:/var/lib/postgresql/data
    networks:
      - keycloak_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d keycloak"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: dbSecurity
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    depends_on:
      dbSecurity:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - keycloak_net
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080; echo -e 'GET /health/ready HTTP/1.1\r\nhost: localhost\r\nConnection: close\r\n\r\n' >&3; timeout --preserve-status 1 cat <&3 | grep -m 1 status | grep -m 1 UP; ERROR=$?; exec 3<&-; exec 3>&-; exit $ERROR" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app_net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=PVjHlx7ESeesq55jeB6Efw
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9090
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9090 --list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - kafka_net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - db_app_mongo

  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
      - 'prometheus_data:/prometheus'
    ports:
      - "9090:9090"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:9090/-/healthy || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  task_service:
    image: dywinar/task-service:latest
    container_name: task
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskDb
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      SPRING_DATASOURCE_URL_REACTIVE: r2dbc:postgresql://db:5432/taskDb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KEYCLOAK_URI: http://keycloak:8080/realms/task
      KAFKA_SERVERS: kafka:9090
      KAFKA_PARTITIONS: 2
      SERVER_PORT: 8000
      PAGE_SIZE: 10
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - monitoring
      - kafka_net
      - app_net
      - keycloak_net
      - db_app

  notifications_service:
    image: dywinar/notifications-service:latest
    container_name: notifications-service
    ports:
      - "8002:8002"
    environment:
      MONGO_USER: mongo
      MONGO_PASSWORD: 123456
      MONGO_URL: mongo:27017
      KEYCLOAK_URI: http://keycloak:8080/realms/task
      KAFKA_SERVERS: kafka:9090
      SERVER_PORT: 8002
      PAGE_SIZE: 10
    depends_on:
      mongo:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - monitoring
      - kafka_net
      - keycloak_net
      - db_app_mongo

  user_service:
    image: dywinar/user-service:latest
    container_name: user_service
    ports:
      - "8001:8001"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CLIENT_ID_CREDENTIALS: ${CLIENT_ID_CREDENTIALS}
      CLIENT_SECRET_CREDENTIALS: ${CLIENT_SECRET_CREDENTIALS}
      KEYCLOAK_URI: http://keycloak:8080/realms/task
      USER_SERVICE_URL: http://task:8000
      SERVER_PORT: 8001
    depends_on:
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - monitoring
      - app_net
      - keycloak_net

volumes:
  db:
  dbSecurity:
  mongo_data:
  kafka_data:
  prometheus_data:

networks:
  keycloak_net:
  monitoring:
  app_net:
  kafka_net:
  db_app:
  db_app_mongo: