
spring:
  application:
    name: notifications-service
  data:
      mongodb:
        uri: mongodb://${MONGO_USER:mongo}:${MONGO_PASSWORD:123456}@${MONGO_URL:localhost:27017}/notifications?authSource=admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/task}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      group-id: notification-consumer-group
      properties:
        spring:
          json:
            trusted:
              packages: "*"
server:
  port: ${SERVER_PORT:8002}

springdoc:
  display-request-duration: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
pageable:
  size: ${PAGE_SIZE:10}

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web.client: DEBUG
    com.mongodb: DEBUG