
spring:
  application:
    name: user-service
  cache:
    type: redis
  data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}
        repositories:
          enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID_CREDENTIALS}
            client-secret: ${CLIENT_SECRET_CREDENTIALS}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/task}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/task}
server:
  port: ${SERVER_PORT:8001}


springdoc:
  display-request-duration: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
client:
  user-service-url: ${USER_SERVICE_URL:http://localhost:8000}
  keycloak-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/task}

logging:
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.web.client: DEBUG
    com.mongodb: DEBUG