
spring:
  application:
    name: task
  cache:
    type: redis
  data:
      redis:
        host: localhost
        port: 6379
        repositories:
          enabled: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/task
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/task
server:
  port: 8001
logging:
  file:
    name: logs/app.log

springdoc:
  swagger-ui:
    display-request-duration: true
management:
  endpoints:
    web:
      exposure:
        include: health, beans, prometheus