
spring:
  application:
    name: task
  liquibase:
    change-log: classpath:db/changelog-master.xml
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskDb}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    enabled: true
  r2dbc :
    url: ${SPRING_DATASOURCE_URL_REACTIVE:r2dbc:postgresql://localhost:5432/taskDb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
server:
  port: 9090
logging:
  file:
    name: logs/app.log
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

springdoc:
  swagger-ui:
    display-request-duration: true
management:
  endpoints:
    web:
      exposure:
        include: health, beans, prometheus